[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

[dependencies]
uint = "0.9.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
